[general]
email = "your_email@example.com"
displayMode = "expanded"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = true
fileWatcherType = "watchdog"

[logger]
level = "info"

[client]
toolbarMode = "auto"